DROP TABLE IF EXISTS topoCimo3;
CREATE TABLE topoCimo3_groupeIACRTopo( 
	topoCimo3 varchar(7) NOT NULL, 
	libelleTopoCimo3 varchar(100) DEFAULT NULL, 
	PRIMARY KEY (topoCimo3) 
) ENGINE=InnoDB DEFAULT CHARSET=latin1; 

INSERT INTO topoCimo3_groupeIACRTopo (topoCimo3, libelleTopoCimo3) VALUES 
('C008',Lésion à localisations contiguës de la lèvre), 
('C006',Commissure des lèvres), 
('C001',Face externe de la lèvre inférieure), 
('C002',Face externe de la lèvre SAI), 
('C005',Muqueuse de la lèvre SAI), 
('C003',Muqueuse de la lèvre supérieure), 
('C009',Lèvre SAI (à l'exclusion de la peau de la lèvre)), 
('C000',Face externe de la lèvre supérieure), 
('C004',Muqueuse de la lèvre inférieure), 
('C019',Base de la langue SAI), 
('C022',Face ventrale de la langue SAI), 
('C021',Bord de la langue), 
('C029',Langue SAI), 
('C020',Face dorsale de la langue SAI), 
('C024',Amygdale linguale), 
('C028',Lésion à localisations contiguës de la langue), 
('C023',Deux tiers antérieurs de la langue SAI), 
('C039',Gencive SAI), 
('C031',Gencive inférieure), 
('C030',Gencive supérieure), 
('C049',Plancher de la bouche SAI), 
('C041',Plancher latéral de la bouche), 
('C040',Plancher antérieur de la bouche), 
('C048',Lésion à localisations contiguës du plancher de la bouche), 
('C058',Lésion à localisations contiguës du palais), 
('C051',Palais mou SAI (à l'exclusion de la face nasopharyngée du palais mou)), 
('C052',Luette), 
('C050',Palais dur), 
('C059',Palais SAI), 
('C069',Bouche SAI), 
('C068',Lésion à localisations contiguës de la bouche), 
('C062',Région rétromolaire), 
('C061',Vestibule de la bouche), 
('C060',Muqueuse de la joue), 
('C079',Glande parotide), 
('C089',Glande salivaire principale SAI), 
('C088',Lésion à localisations contiguës des glandes salivaires principales), 
('C081',Glande sub-linguale), 
('C080',Glande sous-maxillaire), 
('C099',Amygdale SAI (à l'exclusion de l'amygdale linguale et de l'amygdale pharyngée)), 
('C098',Lésion à localisations contiguës de l'amygdale), 
('C091',Pilier de l'amygdale), 
('C090',Loge amygdalienne), 
('C109',Oropharynx SAI), 
('C108',Lésion à localisations contiguës de l'oropharynx), 
('C104',Fente branchiale (en tant que localisation néoplasique)), 
('C103',Paroi postérieure de l'oropharynx), 
('C102',Paroi latérale de l'oropharynx), 
('C101',Face antérieure de l'épiglotte), 
('C100',Vallécule), 
('C119',Nasopharynx SAI), 
('C118',Lésion à localisations contiguës du nasopharynx), 
('C113',Paroi antérieure du nasopharynx), 
('C112',Paroi latérale du nasopharynx), 
('C111',Paroi postérieure du nasopharynx), 
('C110',Paroi supérieure du nasopharynx), 
('C129',Sinus piriforme), 
('C139',Hypopharynx SAI), 
('C132',Paroi postérieure de l'hypopharynx), 
('C138',Lésion à localisations contiguës de), 
('C130',Région rétrocricoïdienne), 
('C131',Face hypopharyngée du repli ary-épiglottique), 
('C140',Pharynx SAI), 
('C148',Lésion à localisations contiguës de la lèvre, de la cavité buccale et du pharynx), 
('C142',Anneau de Waldeyer), 
('C154',Tiers moyen de l'œsophage), 
('C152',Œsophage abdominal), 
('C155',Tiers inférieur de l'œsophage), 
('C151',Œsophage thoracique), 
('C153',Tiers supérieur de l'œsophage), 
('C150',Œsophage cervical), 
('C159',Œsophage SAI), 
('C158',Lésion à localisations contiguës de l'œsophage), 
('C169',Estomac SAI), 
('C168',Lésion à localisations contiguës de l'estomac), 
('C166',Grande courbure de l'estomac SAI (non classable de C16.0 à C16.4)), 
('C165',Petite courbure de l'estomac SAI (non classable de C16.1 à C16.4)), 
('C164',Pylore), 
('C163',Antre gastrique), 
('C162',Corps de l'estomac), 
('C161',Fundus de l'estomac), 
('C160',Cardia SAI), 
('C178',Lésion à localisations contiguës de l 'intestin grêle), 
('C173',Diverticule de Meckel (en tant que localisation d'un néoplasme)), 
('C172',Iléon (à l'exclusion de la valvule iléocaecale)), 
('C171',Jéjunum), 
('C170',Duodénum), 
('C179',Intestin grêle SAI), 
('C182',Côlon ascendant), 
('C181',Appendice), 
('C180',Caecum), 
('C189',Côlon SAI), 
('C186',Côlon descendant), 
('C188',Lésion à localisations contiguës du côlon), 
('C185',Angle splénique du côlon), 
('C184',Côlon transverse), 
('C187',Côlon sigmoïde), 
('C183',Angle hépatique du côlon), 
('C199',Jonction recto-sigmoïdienne), 
('C209',Rectum SAI), 
('C211',Canal anal), 
('C210',Anus SAI (à l'exclusion de la peau de l'anus, péri-anale et de la marge anale  C44.5)), 
('C218',Lésion à localisations contiguës du rectum, de l'anus et du canal anal), 
('C212',Zone cloacale), 
('C221',Voies biliaires intrahépatiques), 
('C220',Foie), 
('C239',Vésicule biliaire), 
('C249',Voies biliaires SAI), 
('C248',Lésion à localisations contiguës des voies biliaires), 
('C241',Ampoule de Vater), 
('C240',Voies biliaires extra-hépatiques), 
('C259',Pancréas SAI), 
('C257',Autres localisations spécifiées du pancréas), 
('C254',Ilôts de Langerhans), 
('C253',Canal pancréatique), 
('C258',Lésion à localisations contiguës du pancréas), 
('C252',Queue du pancréas), 
('C251',Corps du pancréas), 
('C250',Tête du pancréas), 
('C268',Lésion à localisations contiguës de l'appareil digestif), 
('C260',Tractus intestinal SAI), 
('C269',Tractus gastro-intestinal SAI), 
('C301',Oreille moyenne), 
('C300',Fosse nasale (à l'exclusion du nez SAI C76.0)), 
('C319',Sinus annexe SAI), 
('C318',Lésion à localisations contiguës des sinus accessoires), 
('C313',Sinus sphénoïdal), 
('C312',Sinus frontal), 
('C311',Sinus ethmoïdal), 
('C310',Sinus maxillaire), 
('C329',Larynx SAI), 
('C328',Lésion à localisations contiguës du larynx), 
('C323',Cartilage laryngé), 
('C322',Étage sous-glottique), 
('C321',Étage sus-glottique), 
('C320',Glotte), 
('C339',Trachée), 
('C349',Poumon SAI), 
('C348',Lésion à localisations contiguës du poumon), 
('C343',Lobe inférieur du poumon), 
('C342',Lobe moyen du poumon), 
('C341',Lobe supérieur du poumon), 
('C340',Bronche souche), 
('C379',Thymus), 
('C388',Lésion à localisations contiguës du cœur, du), 
('C384',Plèvre SAI), 
('C383',Médiastin SAI), 
('C382',Médiastin postérieur), 
('C381',Médiastin antérieur), 
('C380',Coeur), 
('C390',Voies respiratoires supérieures SAI), 
('C399',Localisations mal définies de l'appareil respiratoire), 
('C398',Lésion à localisations contiguës de l'appareil respiratoire), 
('C400',Os longs du membre supérieur, omoplate et articulations), 
('C409',Os d’un membre SAI), 
('C408',Lésion à localisations contiguës des os, des articulations et des cartilages articulaires des membres inférieurs), 
('C403',Os courts du membre inférieur et articulations), 
('C402',Os longs du membre inférieur et articulations), 
('C401',Os courts du membre supérieur et articulations), 
('C418',Lésion à localisations contiguës des os, des articulations et du cartilage articulaire), 
('C413',Côte, sternum, clavicule et articulations), 
('C419',Os SAI), 
('C412',Colonne vertébrale (à l'exclusion du sacrum et coccyx)), 
('C414',Os du bassin, sacrum, coccyx et cartilage articulaire), 
('C410',Os du crâne, de la face et articulations), 
('C411',Mandibule), 
('C424',Système hématopoïétique SAI), 
('C422',Rate), 
('C421',Moelle osseuse), 
('C423',Système réticulo- endothélial SAI), 
('C420',Sang), 
('C449',Peau SAI (à l'exclusion de la peau de la vulve, des grandes lèvres, du pénis, du scrotum)), 
('C447',Peau de la hanche et du membre inférieur), 
('C446',Peau de l'épaule et du membre supérieur), 
('C445',Peau du tronc), 
('C448',Lésion à localisations contiguës de la peau), 
('C443',Peau des autres régions et des régions non précisées de la face), 
('C442',Oreille externe), 
('C441',Paupière SAI), 
('C444',Peau du crâne et du cou), 
('C440',Peau de la lèvre SAI), 
('C470',Nerfs périphériques et  système nerveux autonome de la tête, de la face et du cou), 
('C478',Lésion à localisations contiguës des nerfs périphériques et du système nerveux autonome), 
('C476',Nerfs périphériques et  système nerveux autonome du tronc), 
('C475',Nerfs périphériques et  système nerveux autonome du pelvis), 
('C479',Système nerveux autonome SAI), 
('C474',Nerfs périphériques et  système nerveux autonome du thorax), 
('C473',Nerfs périphériques et  système nerveux autonome du thorax), 
('C472',Nerfs périphériques et  système nerveux autonome du membre inférieur et de la hanche), 
('C471',Nerfs périphériques et  système nerveux autonome du membre supérieur et de l'épaule), 
('C488',Lésion à localisations contiguës du rétropéritoine et du péritoine), 
('C482',Péritoine SAI), 
('C481',Régions spécifiées du péritoine), 
('C480',Rétropéritoine), 
('C499',Tissu conjonctif, tissu sous-cutané et autres tissus mous, SAI), 
('C498',Lésion à localisations contiguës du tissu conjonctif, du tissu sous-cutané et autres tissus mous), 
('C496',Tissu conjonctif, tissu sous-cutané et autres tissus mous du tronc SAI), 
('C495',Tissu conjonctif, tissu sous-cutané et autres tissus mous du bassin), 
('C494',Tissu conjonctif, tissu sous-cutané et autres tissus mous de l'abdomen), 
('C493',Tissu conjonctif, tissu sous-cutané et autres tissus mous du thorax), 
('C492',Tissu conjonctif, tissu sous-cutané et autres tissus mous de la hanche et du membre inférieur), 
('C491',Tissu conjonctif, tissu sous-cutané et autres tissus mous de l'épaule et du membre supérieur), 
('C490',Tissu conjonctif, tissu sous-cutané et autres tissus mous de la tête, de la face et du cou), 
('C505',Quadrant inféro-externe du sein), 
('C504',Quadrant supéro-externe du sein), 
('C503',Quadrant inféro-interne du sein), 
('C502',Quadrant supéro-interne du sein), 
('C501',Région centrale du sein), 
('C500',Mamelon), 
('C506',Prolongement axillaire du sein), 
('C508',Lésion à localisations contiguës du sein), 
('C509',Sein SAI (à l'exclusion de la peau du sein)), 
('C519',Vulve SAI), 
('C518',Lésion à localisations contiguës de la vulve), 
('C512',Clitoris), 
('C511',Petite lèvre), 
('C510',Grande lèvre), 
('C529',Vagin SAI), 
('C539',Col utérin), 
('C538',Lésion à localisations contiguës du col utérin), 
('C531',Exocol), 
('C530',Endocol), 
('C549',Corps utérin), 
('C548',Lésion à localisations contiguës du corps de l'utérus), 
('C543',Fond utérin), 
('C542',Myomètre), 
('C541',Endomètre), 
('C540',Isthme de l'utérus), 
('C559',Utérus SAI), 
('C569',Ovaire), 
('C573',Paramètre), 
('C572',Ligament rond), 
('C571',Ligament large), 
('C570',Trompe de Fallope), 
('C579',Appareil génital féminin SAI), 
('C578',Lésion à localisations contiguës des organes), 
('C577',Autres régions spécifiées des organes génitaux), 
('C574',Annexes de l'utérus), 
('C589',Placenta), 
('C601',Gland), 
('C602',Corps de la verge), 
('C600',Prépuce), 
('C609',Verge SAI), 
('C608',Lésion à localisations contiguës de la verge), 
('C619',Glande prostatique), 
('C629',Testicule SAI), 
('C621',Testicule intra-scrotal), 
('C620',Testicule ectopique (en tant que localisation néoplasique)), 
('C630',Épididyme), 
('C639',Organes génitaux masculins SAI), 
('C638',Lésion à localisations contiguës des organes masculins), 
('C637',Autres régions spécifiées des organes génitaux masculins), 
('C632',Scrotum SAI), 
('C631',Cordon spermatique), 
('C649',Rein SAI), 
('C659',Bassinet), 
('C669',Uretère), 
('C676',Orifice urétéral), 
('C674',Paroi postérieure de la vessie), 
('C677',Ouraque), 
('C673',Paroi antérieure de la vessie), 
('C672',Paroi latérale de la vessie), 
('C671',Dôme de la vessie), 
('C675',Col vésical), 
('C670',Trigone de la vessie), 
('C679',Vessie SAI), 
('C678',Lésion à localisations contiguës de la vessie), 
('C689',Appareil urinaire SAI), 
('C688',Lésion à localisations contiguës de l' appareil urinaire), 
('C681',Glande para-urétrale), 
('C680',Urètre), 
('C699',Œil SAI), 
('C698',Lésion à localisations contiguës de l'œil et des annexes), 
('C696',Orbite SAI), 
('C695',Glande lacrymale), 
('C694',Corps ciliaire), 
('C693',Choroïde), 
('C692',Rétine), 
('C691',Cornée SAI), 
('C690',Conjonctive), 
('C709',Méninges SAI), 
('C701',Méninges rachidiennes), 
('C700',Méninges cérébrales), 
('C718',Lésion à localisations contiguës du cerveau), 
('C717',Tronc cérébral), 
('C716',Cervelet SAI), 
('C715',Ventricule SAI), 
('C714',Lobe occipital), 
('C713',Lobe pariétal), 
('C712',Lobe temporal), 
('C711',Lobe frontal), 
('C710',Cerveau), 
('C719',Encéphale SAI), 
('C721',Queue de cheval), 
('C722',Nerf olfactif), 
('C728',Lésion à localisations contiguës du cerveau et du système nerveux central), 
('C724',Nerf acoustique (vestibulo-cochléaire)), 
('C729',Système nerveux SAI), 
('C723',Nerf optique), 
('C725',Nerf crânien SAI), 
('C720',Moelle épinière), 
('C739',Glande thyroïde), 
('C749',Glande surrénale SAI), 
('C741',Médullosurrénale), 
('C740',Cortex surrénalien), 
('C751',Glande hypophysaire), 
('C750',Glande parathyroïde), 
('C759',Glande endocrine SAI), 
('C758',Lésion à localisations contiguës des glandes endocrines), 
('C755',Corpuscule aortique et autres paraganglions), 
('C754',Corpuscule carotidien), 
('C753',Glande pinéale), 
('C752',Canal craniopharyngé), 
('C768',Lésion à localisations contiguës des régions mal définies), 
('C767',Autres régions mal définies), 
('C765',Membre inférieur SAI), 
('C764',Membre supérieur SAI), 
('C763',Bassin SAI), 
('C762',Abdomen SAI), 
('C761',Thorax SAI), 
('C760',Tête, face ou cou SAI), 
('C771',Ganglions lymphatiques intra-thoraciques), 
('C770',Ganglions lymphatiques de la tête, de la face et du cou), 
('C779',Ganglion lymphatique SAI), 
('C778',Ganglions lymphatiques de régions multiples), 
('C775',Ganglions lymphatiques pelviens), 
('C774',Ganglions lymphatiques de la région inguinale ou de la jambe), 
('C773',Ganglions lymphatiques de l'aisselle ou du bras), 
('C772',Ganglions lymphatiques intra-abdominaux), 
	('C809',Siège primaire non précisé); 
